apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-api
  labels:
    app: template
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
      type: api
  template:
    metadata:
      labels:
        app: template
        type: api
    spec:
      containers:
        - name: template-api
          image: template/api
          imagePullPolicy: "IfNotPresent"
          env:
            - name: TEMPLATE_USERNAME
              value: "myusername"
            - name: TEMPLATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: template-secret
                  key: password
          ports:
            - containerPort: 3001
