apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-frontend
  labels:
    app: template
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
      type: frontend

  template:
    metadata:
      labels:
        app: template
        type: frontend

    spec:
      containers:
        - name: template-frontend
          image: template/frontend
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
